# Generated by Django 2.0.8 on 2018-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180928_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.TextField(blank=True, null=True, verbose_name='Basket'),
        ),
    ]
